version: "3.9"

services:
 backend:
    build: .
    container_name: collegebuddy_backend
    ports:
      - "8080:8080"
    networks: 
      - collegebuddy_network
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_TIMEZONE: ${DB_TIMEZONE}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      EXTENSION_ID: ${EXTENSION_ID}
      DATABASE_URL: ${DATABASE_URL}
volumes:
  pgdata:

networks:
  collegebuddy_network:
