version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: collegebuddy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - collegebuddy_network
  backend:
    build: .
    container_name: collegebuddy_backend
    ports:
      - "8080:8080"
    networks: 
      - collegebuddy_network
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_TIMEZONE: ${DB_TIMEZONE}
      JWT_SECRET: ${JWT_SECRET}
      APP_PORT: ${APP_PORT}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      EXTENSION_ID: ${EXTENSION_ID}
      DATABASE_URL: ${DATABASE_URL}
volumes:
  pgdata:

networks:
  collegebuddy_network:
